#!/bin/sh -

#	@(#)netstart	5.2.1 (2.11BSD) 1996/11/16

INET=`testnet`
if [ $INET = YES ]; then
	echo Assuming NETWORKING system ...		>/dev/console 2>&1
else
	echo Assuming non-networking system ...		>/dev/console 2>&1
fi
export INET

# DON'T EVEN THINK ABOUT RUNNING ROUTED ON A PDP-11!!!  Just set routedflags
# to "NO" and set up a default gateway below.
#
routedflags=NO
rwhod=YES
named=NO

# myname is my symbolic name
# my-netmask is specified in /etc/networks
# my-default-address should be set to some machine where you
#	want to send all your packets, by default.
#

hostname=pdp1153.murgatroid.com
netmask=255.255.0.0
broadcast=10.0.255.255
default=10.0.0.254

hostname $hostname					>/dev/console 2>&1
hostid $hostname					>/dev/console 2>&1

if [ $INET = YES ]; then
	ifconfig qe0 inet netmask $netmask $hostname broadcast $broadcast up -trailers >/dev/console 2>&1
	ifconfig lo0 inet localhost up -trailers	>/dev/console 2>&1

	route add $hostname localhost 0		>/dev/console 2>&1
	route add default $default 1		>/dev/console 2>&1
fi
