#!/bin/sh -

#	@(#)netstart	5.2.1 (2.11BSD) 1996/11/16

INET=`testnet`
if [ $INET = YES ]; then
	echo Assuming NETWORKING system ...		>/dev/console 2>&1
else
	echo Assuming non-networking system ...		>/dev/console 2>&1
fi
export INET

# DON'T EVEN THINK ABOUT RUNNING ROUTED ON A PDP-11!!!  Just set routedflags
# to "NO" and set up a default gateway below.
#
routedflags=NO
rwhod=YES
named=NO

#
# At PL457, 2.11BSD will not look at /etc/hosts if /etc/resolv.conf
# exists.  So if /etc/resolv.conf exists, we have trouble bringup the
# network because we can't resolve the hostnames (because the network
# isn't up).
#
# So, move /etc/resolv.conf out of the way and put it in back, if we
# are bringing up networking.  If your DNS and /etc/hosts disagree ...
mv /etc/resolv.conf /etc/resolv.conf.keep

hostname=pdp1153.murgatroid.com
netmask=255.255.0.0
broadcast=10.0.255.255
default=10.0.0.254
localhost=localhost

hostname $hostname					>/dev/console 2>&1
hostid $hostname					>/dev/console 2>&1

if [ $INET = YES ]; then
	ifconfig qe0 inet netmask $netmask $hostname broadcast $broadcast up -trailers >/dev/console 2>&1
	ifconfig lo0 inet $localhost up -trailers	>/dev/console 2>&1

	route add $hostname $localhost 0		>/dev/console 2>&1
	route add default $default 1		>/dev/console 2>&1

	mv /etc/resolv.conf.keep /etc/resolv.conf
fi
